### ISSUE TITLE
[BUG] "isGroup" is true even when message is undo-ed in dms

### ISSUE THREAD

**Issue by Rylazius** [RFS-ADRENO/zca-js#25]
**Describe the bug**
title

**To Reproduce**

1. Add this:
`
listener.on("undo", async (undo) => {
  console.log(undo);
});
`
2. Run
3. Undo a message in DMs
4. See "isGroup" value

**Expected behavior**
"isGroup" value = false

**Screenshots**
![image](https://github.com/user-attachments/assets/15ad47d5-0b50-4993-8754-7ef7b62b3fb6)
![image](https://github.com/user-attachments/assets/8506cce2-255e-4f9d-83d8-72bb4ccbf5bd)

**Desktop (please complete the following information):**

-   OS: Arch Linux
-   Browser: Firefox
-   Version: 131.03

**Smartphone (please complete the following information):**

-   Device: iPad Pro 3rd gen
-   OS: iOS 18.1
-   Browser: Safari
-   Version: idk

**Comment by lattaai1** [comment]
Hello, I tried to fix the issue

This is what I did:
I've identified the issue in the Undo class constructor. The isGroup parameter was not being used correctly. I've updated the constructor to properly set the isGroup property based on the passed parameter. This change ensures that the isGroup value will be false for Undo events in direct messages.

I also created pull request: https://github.com/RFS-ADRENO/zca-js/pull/26


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
